
export  const SEARCH_KEYWORD = 'SEARCH_KEYWORD';

//category
export const GET_LOGIN = 'GET_LOGIN';
export const GET_LOGIN_SUCCESS  = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR';

//type_category
export const DATA_FROM_CATEGORY = 'DATA_FROM_CATEGORY';
export const DATA_FROM_CATEGORY_SUCCESS = 'DATA_FROM_CATEGORY_SUCCESS';
export const DATA_FROM_CATEGORY_ERROR = 'DATA_FROM_CATEGORY_ERROR';
export const CLEAR_CATEGORY_DATA = 'CLEAR_CATEGORY_DATA';

// recommend
export const GET_RECOMMEND = 'GET_RECOMMEND';
export const GET_RECOMMEND_SUCCESS = 'GET_RECOMMEND_SUCCESS';
export const GET_RECOMMEND_ERROR = 'GET_RECOMMEND_ERROR';
